### ISSUE TITLE
ラジオネームが保存されるようにする

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-client-member#242]
## やってほしいこと
- アーキテクチャについて勉強する
- PRの出し方について勉強する
- 曲のリクエスト時にラジオネームが入力されていたら、そのラジオネームをlocalStorage上に保存するようにする(ここはDiscordでペアプロしましょう)
(保存したラジオネームを取得して表示するタスクは別で切り出してやりましょう)

## アーキテクチャについて
- [DJ System Frontend Architecture · Discussion #39 · lit-kansai/dj_system-docs](https://github.com/lit-kansai/dj_system-docs/discussions/39)
コレ読んでほしいです。できれば手も動かしてもらえると

## PRの出し方
一緒にやりましょう。でもどういう仕組みかについては知っておいた方がいいと思うのでこれ読んでおいてください↓
https://backlog.com/ja/git-tutorial/pull-request/01/

### 参考画像
これ
<img width="500"  src="https://user-images.githubusercontent.com/22112440/194482628-b920937d-a303-4674-a142-cf9008f2472e.png" >

## 具体的にやったほしいこと
具体的にやってほしいことは以下のとおりです。
- ラジオネームが入力されていたらlocalStorage上に保存する

#### 1. ラジオネームを管理するRepositoryを作る

- `core/02-repositories/radioName/index.ts`を作る
- `core/02-repositories/radioName/index.ts`に`IRadioNameReposiotry`というinterfaceと`RadioNameReposiotry`というクラスを作る
- `IRadioNameReposiotry`にはlocalStorageにラジオネームを保存する関数とラジオネームを取得する関数を定義する
- interfaceに定義したメソッドを実装する

#### 2. Repositoryを使う
- `03/composables/useRequestMusicModal`で曲のリクエストが走った時の処理を管理してるので、ここで曲がリクエストされたときにラジオネームも同時に保存する処理を追加する

**Comment by Tomoya113** [comment]
そうえいば東田先生の奴あるからコレ読んだらええやん
https://zenn.dev/penguin4731/books/11bee5738e367f/viewer/ecfd5e

**Comment by Tomoya113** [comment]
Modal周りの処理汚すぎるのでちょっとリファクタリングするわ

**Comment by Tomoya113** [comment]
あ、ちなみに全然Repository作るところは進めてもらってOK

**Comment by txxxxc** [comment]
保存するRepositoryはできたのでClose
